apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-sedvjzta
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-sedvjzta:467ca64170f85e8da986aeb370c56ba1ec51c555@sha256:fda34339aa602363e319ef03f98027b489ccdbddf4ff3c206e0c7f64df66f4a2
          name: container-image
